### ISSUE TITLE
Port small caps from TG Termes

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [khaledhosny/xits#58]
TeX Gyre Termes is a Times like font created by GUST, in this font I found several glyphs designed as small caps. This font released under LaTeX and GUST licenses does these licenses compatitable with OFL? If so, I think it’s possible to add small caps into XITS font.

**Comment by khaledhosny** [comment]
TG Termes has an incompatible license.

**Comment by rstub** [comment]
@khaledhosny It is clear that one cannot copy from a OFL licensed font to a LPPL licensed font, since OFL is a copyleft license. But where do you see the incompatibility for the other direction? To me that is analogous to using MIT licensed code in a GPL licensed program, which is quite common.

BTW, even then I would not use the SC from TG Termes. For example /o.sc looks really strange ...

**Comment by khaledhosny** [comment]
I’m not a lawyer and I don’t know what are the implications of copying LPPL licensed glyphs to an OFL licensed font, and I’m pretty sure no one tried to find an answer for this before. Like you said, that is a moot point anyway given the oddities of TG Terms design.

**Comment by dbenjaminmiller** [comment]
The clauses at hand are the following:

```
 6. If you are not the Current Maintainer of the Work, you may distribute a Derived Work provided the following conditions are met for every component of the Work unless that component clearly states in the copyright notice that it is exempt from that condition. Only the Current Maintainer is allowed to add such statements of exemption to a component of the Work.

a. If a component of this Derived Work can be a direct replacement for a component of the Work when that component is used with the Base Interpreter, then, wherever this component of the Work identifies itself to the user when used interactively with that Base Interpreter, the replacement component of this Derived Work clearly and unambiguously identifies itself as a modified version of this component to the user when used interactively with that Base Interpreter.

b. Every component of the Derived Work contains prominent notices detailing the nature of the changes to that component, or a prominent reference to another file that is distributed as part of the Derived Work and that contains a complete and accurate log of the changes.

c. No information in the Derived Work implies that any persons, including (but not limited to) the authors of the original version of the Work, provide any support, including (but not limited to) the reporting and handling of errors, to recipients of the Derived Work unless those persons have stated explicitly that they do provide such support for the Derived Work.
```
Because of the additional requirements beyond the GPL's, for example, this license is not compatible with the GPL. The OFL requires that the entire derivative font be distributed only under the terms of the OFL. My interpretation, then, is that LPPL fonts cannot be merged into OFL fonts without permission to relicense, as this would subject the user to requirements not in the OFL. (Though I am not a lawyer.)

In any case, the glyphs aren't of great quality anyway.

**Comment by callegar** [comment]
Even if the bug is closed, I would like to add a quick note to agree with @rstub while saying "I would not use the SC from TG Termes". The Small Caps in TG Termes are more like Petite Caps.

**Comment by rstub** [comment]
@callegar They are not only Petite Caps, at least some letters are also to wide for their height. Compare `O\textsc{o}o` for TG Termes:

![image](https://user-images.githubusercontent.com/27821131/62947506-edb79200-bde2-11e9-90b9-2c2ef6b1d8e0.png)

This can be seen in several TeX Gyre fonts, e.g. Pagella

![image](https://user-images.githubusercontent.com/27821131/62947604-1c356d00-bde3-11e9-8ce7-5a20610b9a57.png)

**Comment by callegar** [comment]
@rstub, you are right! It is worth noticing that TG fonts do not have "real" small caps, but so called "mechanical" small caps obtained by alogorithmically scaling the capital letters, which I believe is the origin of most of these issues (too small scale -> petite caps in place of small caps, no ad hoc horizontal scaling, at least for some glyphs -> too large small caps letter).

In some sense, this is not totally bad news, though. On one hand, things that are algorithmically generated can be fixed by retouching the algorithm. On the other hand, one may think of using a similar approach on XITS. However I cannot find the TG metatype1 sources, nor it is clear to me if there are easy ways to practice algorithmic transformations with FontForge or if there are paths from FontForge to metatype1 and viceversa (I am not a font expert by any means).

**Comment by KrasnayaPloshchad** [comment]
@rstub Oh, that is similar to Doulos SIL, not like what thay claimed in their presentation.

**Comment by callegar** [comment]
Well, sort of midway. To the best of my understanding there is an algorithmic transformation practiced at the Metatype1 level, which provides a lot of adjustment: non uniform scaling and thickening of the result with an asymmetric pen. I think that the presentation offers a code sample for the letter 'h'.

**Comment by dbenjaminmiller** [comment]
TeX Gyre Termes X tries to fix the issues. And I was not under the impression TG was designed in MT1; in any case, the fonts are unusable for licensing reasons. I think we should be going to mimic the Adobe design in any case.
